[project]
name = "chatterboxmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [

    "chatterbox-tts",
    "common-schemas"
]

[tool.uv.sources]
common-schemas = { path = "../../../../libs/common-schemas" }

